name: TribeCrafts
version: 1.13.2
main: me.nowaha.tribecrafts.TribeCrafts
api-version: 1.13
authors: [Nowaha]
description: Custom crafting recipes
website: www.noahverkaik.com
depend:
  - InfiniteChests
